FROM eoflibrary/eof_elmer84_of6:latest

WORKDIR /home/openfoam

# Remove the EOF-Library that ships inside the base image
RUN rm -rf EOF-Library

# This assumes you run `docker build` from your EOF fork root,
COPY . EOF-Library

WORKDIR /home/openfoam/EOF-Library

# Add alias for initializing and building the project
RUN echo 'alias init="cd ~ && eofCompile && cd EOF-Library && wmake solvers/mdhLinearHall && cp -r tests/linearHall runs && cd runs/linearHall "' >> ~/.bashrc
RUN echo 'alias generate_mesh="cd ~/EOF-Library/runs/linearHall && blockMesh && ElmerGrid 14 2 channel.msh -out meshElmer"' >> ~/.bashrc
RUN echo 'alias configure_elmer="cd ~/EOF-Library/runs/linearHall && echo \"case.sif\" > ELMERSOLVER_STARTINFO"' >> ~/.bashrc
RUN echo 'alias run_sim="cd ~/EOF-Library/runs/linearHall && mpirun -n 1 mdhLinearHall : -n 1 ElmerSolver_mpi case.sif"' >> ~/.bashrc

RUN echo 'alias run_all="init && generate_mesh && configure_elmer && run_sim"' >> ~/.bashrc