FROM eoflibrary/eof_elmer84_of6:latest

WORKDIR /home/openfoam

# Remove the EOF-Library that ships inside the base image
RUN rm -rf EOF-Library

# This assumes you run `docker build` from your EOF fork root,
COPY . EOF-Library

WORKDIR /home/openfoam/EOF-Library

# Add alias for initializing and building the project
RUN echo 'alias init="cd ~ && eofCompile && cd EOF-Library && wmake solvers/mhdThermoInterFoam5 && cp -r tests/linearHall runs && cd runs/linearHall "' >> ~/.bashrc
RUN echo 'alias generate_mesh="cd ~/EOF-Library/runs/linearHall && blockMesh && setFields && decomposePar"' >> ~/.bashrc
RUN echo 'alias init_elmer="cd ~/EOF-Library/runs/linearHall && ElmerGrid 14 2 . -out meshElmer && ElmerGrid 2 2 meshElmer -metis 2"' >> ~/.bashrc
RUN echo "case.sif" > ELMERSOLVER_STARTINFO
RUN echo 'alias run_sim="cd ~/EOF-Library/runs/linearHall && mpirun -n 2 mhdThermoInterFoam5 -parallel : -n 2 ElmerSolver_mpi case.sif"' >> ~/.bashrc

RUN echo "alias run_all='init && generate_mesh && init_elmer && run_sim'" >> ~/.bashrc